version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWD=pswd
    depends_on:
      - db

  db:
    image: postgres:latest
    # Указываем пароль для пользователя postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pswd
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
